language: node_js  #設置語言

node_js: stable  #設置相應的版本

cache:
    apt: true
    directories:
      - node_modules # 緩存不經常更改的內容

before_install:
  - echo 安装hexo相关环境...

install:
  # - npm install -g cnpm --registry=https://registry.npm.taobao.org
  - npm install

before_script:
  - echo 清空缓存静态文件
  - hexo clean  # 清除
  - echo 生成静态文件...
  - hexo g  # 生成
  - cd ./public
  - ls -l

script:
  - echo 开始部署...
  - git init
  - git config --global user.name "${GH_username}"  #修改name
  - git config --global user.email "${GH_useremail}"  #修改email
  - git add ./
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名稱

# before_cache:
# after_success:
# after_failure:
# before_deploy:
# deploy:
# after_deploy:

after_script:
  - echo 部署完成！
  - echo $HOME
  - $HOME
  - echo $PATH
  - $PATH 
branches:
  only:
    - master #只監測master分支，master是我的博客源碼分支的名稱，可根據自己情況設置
env:
  global:
    - GH_REF: github.com/zhangjichengcc/bolg.git #設置GH_REF，注意更改yourname
    - GH_username: zhangjichengcc
    - GH_useremail: zhangjichengcc@163.com