language: node_js
node_js: stable
cache:
  apt: true
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_8dae3701ae37_key -iv $encrypted_8dae3701ae37_iv
  -in id_rsa_github.enc -out ~\.ssh\\id_rsa_github -d
- echo 安装hexo相关环境...
install:
- npm install gitbook & npm install gitbook-cli
before_script:
- echo 依赖安装完成
script:
- echo 开始编译...
- gitbook init
- gitbook build
after_script:
- echo 编译完成，开始部署！
- echo $HOME
- "$HOME"
- echo $PATH
- "$PATH"
branches:
  only:
  - master
env:
  global:
  - GH_ServerIp: 118.190.52.53
  - GH_username: zhangjichengcc
  - GH_useremail: zhangjichengcc@163.com
